# yaml-language-server: $schema=https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json

Transform: AWS::Serverless-2016-10-31

Description: URL shortener using github as storage

Parameters:
  GithubToken:
    Description: Github access token
    Type: String
  GithubRepo:
    Description: Repo path
    Type: String

Globals:
  Function:
    Architectures:
      - arm64
    MemorySize: 512
    CodeUri: .
    Runtime: python3.13
    Timeout: 100
    Environment:
      Variables:
        GITHUB_ACESS_TOKEN: !Ref GithubToken
        URL_REPO: !Ref GithubRepo

Resources:
  api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  encode:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.encode
      Events:
        apiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref api
            Path: /encode
            Method: GET

  decode:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.decode
      Events:
        apiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref api
            Path: /decode/{url}
            Method: GET
